content: Select a Build!

# Additional links that should be displayed in the initial message.
buttons: 
  - customId: "liveInteraction#characters/cryo/aloy/freeze"
    style: "PRIMARY"
    label: Freeze
    emoji: "<:Element_Cryo:945557264578781235> "

  - customId: "liveInteraction#characters/cryo/aloy/quickswap"
    emoji: "<:Element_Cryo:945557264578781235> "
    style: "PRIMARY"
    label: Quickswap
