content: Select a Build!

# Additional links that should be displayed in the initial message.
buttons: 
  - customId: "liveInteraction#characters/cryo/ganyu/melt"
    style: "PRIMARY"
    label: Ganyu Melt
    emoji: "<:Element_Pyro:945557264792707083> "

  - customId: "liveInteraction#characters/cryo/ganyu/freeze"
    emoji: "<:Element_Cryo:945557264578781235>"
    style: "PRIMARY"
    label: Ganyu Freeze
